
build:
	@spm build

deploy:
	@rm -rf ../../sea-modules/gallery/exMath
	@mkdir  ../../sea-modules/gallery/exMath
	@mkdir  ../../sea-modules/gallery/exMath/1.0.0
	@cp     dist/*.* ../../sea-modules/gallery/exMath/1.0.0
	@echo
	@echo   " deploy to seajs-modules/gallery/exMath/1.0.0"
	@echo
